name: cook19
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dialog_flowtter: ^0.1.3
  google_fonts: ^1.0.0
  bottom_navy_bar: ^3.0.0
  shared_preferences: ^0.5.7
  provider: ^4.0.5
  firebase_database: ^3.1.1
  #firebase_auth: ^0.15.4
  splashscreen : 1.2.0
  flutter_signin_button: ^1.0.0
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  firebase_storage: ^3.1.3
  image_picker: ^0.6.3+4
  google_sign_in: ^4.5.1
  fluttertoast: ^4.0.0
  dynamic_theme: ^1.0.1
  theme_provider: ^0.4.0+1

  firebase_core: ^0.4.0

  firebase_messaging: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/dialog_flow_auth.json
    